### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by jiangmingbuaa** [littleprince1121/AAAI2022-IEEE-for-MMReID#1]
请问这篇paper在哪里可以下载到吗？AAAI的官网上好像没有找到。thanks!

**Comment by ziwang1121** [comment]
可以的哈，论文就在这个项目里。您找一下，有一个pdf文件在最外面一级文件夹里，名称就是论文题目。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "littleprince1121/AAAI2022-IEEE-for-MMReID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月13日(星期天) 晚上8:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[littleprince1121/AAAI2022-IEEE-for-MMReID] About the paper (Issue #1)





 
请问这篇paper在哪里可以下载到吗？AAAI的官网上好像没有找到。thanks!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiangmingbuaa** [comment]
看到了，谢谢!

**Comment by ziwang1121** [comment]
不客气



发自我的iPhone


------------------ Original ------------------
From: jiangmingbuaa ***@***.***&gt;
Date: Sun,Mar 13,2022 9:06 PM
To: littleprince1121/AAAI2022-IEEE-for-MMReID ***@***.***&gt;
Cc: littleprince1121 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [littleprince1121/AAAI2022-IEEE-for-MMReID] About the paper(Issue #1)
